server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: pr-base
          uri: lb://pr-base/ativos
          predicates:
            - Path=/ativos/**
        - id: pr-base
          uri: lb://pr-base/records
          predicates:
            - Path=/records/**
        - id: pr-search
          uri: lb://pr-search/search
          predicates:
            - Path=/search/**
  application:
    name: gateway-service