version: "3"

services:
  varredura-database:
    image: postgres:12.10-alpine
    container_name: varredura-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=varredura
    networks:
      - pr-varredura

  pr-eureka-server:
    container_name: pr-eureka-server
    build: 
      context: ./backend/pr-eureka-server/
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - pr-varredura

  pr-gateway:
    container_name: pr-gateway
    build:
      context: ./backend/pr-gateway/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - pr-eureka-server
    networks:
      - pr-varredura

  pr-base:
    container_name: pr-base
    build:
      context: ./backend/pr-base/
      dockerfile: Dockerfile
    depends_on:
      - pr-eureka-server
      - varredura-database
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:postgresql://varredura-database:5432/varredura
    networks:
      - pr-varredura

  pr-search:
    container_name: pr-search
    build:
      context: ./backend/pr-search/
      dockerfile: Dockerfile
    depends_on:
      - pr-eureka-server
    networks:
      - pr-varredura

networks:
  pr-varredura:
